BulkyBookWebNew/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Data;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CategoryController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CategoryController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }
    public IActionResult Index(string? sort = null)
    {
        IEnumerable<Category> obj;
        if (sort != null)
        {
            obj = _unitOfWork.Category.GetAll().OrderBy(c => c.DisplayOrder);
            if (sort == "dsc")
            {
                obj = obj.Reverse();
            }
        } else
        {
            obj = _unitOfWork.Category.GetAll();
        }
        return View(obj);
    }
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Category obj)
    {

        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("Error", "Something wrong, Check your data");
            return View(obj);
        }

        var isNameAlreadyTaken = _unitOfWork.Category.GetFirstOrDefault(e => e.Name == obj.Name);

        if (isNameAlreadyTaken != null)
        {
            ModelState.AddModelError("name", "Your Name category is already taken");
            return View(obj);
        }
        _unitOfWork.Category.Add(obj);
        await _unitOfWork.Save();
        TempData["success"] = "Category created succesfully";
        return RedirectToAction("Index");
    }

    public IActionResult Edit(int id)
    {
        var obj = _unitOfWork.Category.GetFirstOrDefault(e => e.Id == id);
        if (obj == null)
        {
            TempData["unsuccess"] = "The data is not in our server";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Category obj)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("Error", "Something wrong, Check your data");
            return View(obj);
        }

        var isNameAlreadyTaken = _unitOfWork.Category.GetFirstOrDefault(e => e.Name == obj.Name, noTrack: true);

        if (isNameAlreadyTaken != null && isNameAlreadyTaken.Id != obj.Id)
        {
            ModelState.AddModelError("name", "Your Name category is already taken");
            return View(obj);
        }
        _unitOfWork.Category.Update(obj);
        await _unitOfWork.Save();
        TempData["success"] = "Category edited succesfully";
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        var obj = _unitOfWork.Category.GetFirstOrDefault(e => e.Id == id);
        if (obj == null)
        {
            TempData["unsuccess"] = "The data is not in our server";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(Category obj)
    {
        _unitOfWork.Category.Remove(obj);
        await _unitOfWork.Save();
        TempData["success"] = "Category deleted succesfully";
        return RedirectToAction("Index");
    }
}

BulkyBookWebNew/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]

public class CompanyController : Controller
{
	private readonly IUnitOfWork _unitOfWork;

	public CompanyController(IUnitOfWork unitOfWork)
	{
		_unitOfWork = unitOfWork;
	}

	public IActionResult Index()
	{
		return View();
	}

	public IActionResult Upsert(int? id)
	{
		if (id == 0 || id == null)
		{
			return View();
		}
		var obj = _unitOfWork.Company.GetFirstOrDefault(c => c.Id == id);
		return View(obj);
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Upsert(Company obj) // update and insert
	{

		if (!ModelState.IsValid)
		{
			ModelState.AddModelError("Error", "Something wrong, Check your data");
			return View(obj);
		}

		if (obj.Id == 0)
		{
			_unitOfWork.Company.Add(obj);
			TempData["success"] = "Company created succesfully";
		} else
		{
			_unitOfWork.Company.Update(obj);
			TempData["success"] = "Company edited succesfully";
		}
		await _unitOfWork.Save();
		return RedirectToAction("Index");
	}

	public async Task<IActionResult> Delete(int id)
	{
		var obj = _unitOfWork.Company.GetFirstOrDefault(e => e.Id == id);
		if (obj == null)
		{
			return Json(new
			{
				success = false,
				message = "Error while deleting"
			});
		}
		_unitOfWork.Company.Remove(obj);
		await _unitOfWork.Save();
		return Json(new { 
			success = true, 
			message = "Delete Successful" 
		});
	}

	//[HttpGet]
	public IActionResult GetAll()
	{
		var companyList = _unitOfWork.Company.GetAll();

		return Json(new { data = companyList });
	}

}

BulkyBookWebNew/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]

public class ProductController : Controller
{
	private readonly IUnitOfWork _unitOfWork;
	private readonly IWebHostEnvironment _webHostEnvironment;

	public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
	{
		_unitOfWork = unitOfWork;
		_webHostEnvironment = webHostEnvironment;
	}
	public IActionResult Index()
	{
		return View();
	}
	public IActionResult Upsert(int? id)
	{
		var productVM = new ProductViewModel()
		{
			Product = new(),
			CategoryList = _unitOfWork.Category.GetAll()
			.Select(c =>
			new SelectListItem
			{
				Text = c.Name,
				Value = c.Id.ToString()
			}),
			CoverTypeList = _unitOfWork.CoverType.GetAll()
			.Select(c =>
			new SelectListItem
			{
				Text = c.Name,
				Value = c.Id.ToString()
			})
		};
		if (id == 0 || id == null)
		{
			// Create Product
			//ViewData["CoverTypeList"] = CoverTypeList;
			//ViewBag.CategoryList = CategoryList;
			return View(productVM);

		} else
		{
			// Update Product
			productVM.Product = _unitOfWork.Product.GetFirstOrDefault(p => p.Id == id);
			return View(productVM);
		}

	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Upsert(ProductViewModel obj, IFormFile? file)
	{
		if (ModelState.IsValid)
		{
			string wwwRootPath = _webHostEnvironment.WebRootPath;
			if (file != null)
			{
				string fileName = Guid.NewGuid().ToString();
				var uploads = Path.Combine(wwwRootPath, @"images\products");
				var extension = Path.GetExtension(file.FileName);

				// delete image
				if (obj.Product.ImageUrl != null)
				{
					var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
					if (System.IO.File.Exists(oldImagePath))
					{
						System.IO.File.Delete(oldImagePath);
					}
				}

				using var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create);
				file.CopyTo(fileStream);

				obj.Product.ImageUrl = @"\images\products\" + fileName + extension;
			}

			if (obj.Product.Id == 0)
			{
				_unitOfWork.Product.Add(obj.Product);
				TempData["success"] = "Product created succesfully";
			} else
			{
				_unitOfWork.Product.Update(obj.Product);
				TempData["success"] = "Product updated succesfully";
			}
			await _unitOfWork.Save();
			return RedirectToAction("Index");
		}
		return View(obj);
	}

	#region API CALLS
	[HttpGet]
	public IActionResult GetAll()
	{
		var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
		
		return Json(new {data = productList});
	}

	[HttpDelete]
	public async Task<IActionResult> Delete(int? id)
	{
		var obj = _unitOfWork.Product.GetFirstOrDefault(e => e.Id == id);
		if (obj == null)
		{
			return Json(new { success = false, message = "Error while deleting" });
		}

		var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
		if (System.IO.File.Exists(oldImagePath))
		{
			System.IO.File.Delete(oldImagePath);
		}
		_unitOfWork.Product.Remove(obj);
		await _unitOfWork.Save();
		return Json(new { 
			success = true, 
			message = "Delete Successful" 
		});
	}
	#endregion
}

BulkyBookWebNew/ViewComponents/ShoppingCartViewComponent.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.ViewComponents;

public class ShoppingCartViewComponent : ViewComponent
{
	private readonly IUnitOfWork _unitOfWork;
	public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
	{
		_unitOfWork = unitOfWork;
	}

	public async Task<IViewComponentResult> InvokeAsync()
	{
		var claimsIdentity = (ClaimsIdentity)User.Identity;
		var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
		if (claim != null)
		{
			if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
			{
				HttpContext.Session.SetInt32(SD.SessionCart,
					_unitOfWork.ShoppingCart.GetAll(sc => sc.ApplicationUserId == claim.Value).ToList().Count);
			}

			return View("Default", HttpContext.Session.GetInt32(SD.SessionCart));
		} else
		{
			HttpContext.Session.Clear();
			return View("Default", 0);
		}
	}
}

BulkyBookWebNew/Views/Shared/_FilterProductListPartial.cshtml
@model BulkyBook.Models.ViewModels.HomeViewModel

@foreach (var product in Model.Products)
{
	<div class="col-lg-3 col-md-6">
		<div class="row p-2">
			<div class="col-12 p-1" style="border: 1px solid #008cba; border-radius: 5px;">
				<div class="card">
					<img src="@product.ImageUrl" class="card-img-top rounded" />
					<div class="card-body">
						<div class="text-center" style="height: 5rem">
							<p class="card-title h5 text-primary fs-4">@product.Title</p>
							<p class="card-title h5 text-info" style="font-size: 14px">by <b>@product.Author</b></p>
						</div>
						<div class="pl-1 d-flex justify-content-between">
							<p class="text-end text-warning">List Price: <strike><b>$@product.ListPrice.ToString("0.00")</b></strike></p>
							<p class="text-end text-success"><b>$@product.Price100.ToString("0.00")</b></p>
						</div>
					</div>
				</div>
				<div>
					<a asp-action="Details" asp-route-productId="@product.Id" class="btn btn-primary form-control">Details</a>
				</div>
			</div>
		</div>
	</div>
}

BulkyBookWebNew/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib//bootstrap//dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header class="">
        <nav class="ps-5 pe-3 navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home
                            </a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a> 
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
                                Manage Order
                            </a>
                        </li>

  @*                      @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.SessionCart) != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart"></i> &nbsp;
                                    (@HttpContextAccessor.HttpContext.Session.GetInt32(SD.SessionCart))
                                </a>
                            </li>
                        } else
                        {*@
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
            @*<form class="d-flex">
                <input class="form-control me-sm-2" type="search" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-5">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary text-end">
        <div class="container">
            &copy; 2023 - BulkyBookWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/lib/jquery/dist/jquery.transit.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/flzpy80yuozk4syqvk49h33mw0i33uhlxgqvuzsnrsu3arqv/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWebNew/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
@if (TempData["success"] != null)
{
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}

@if (TempData["unsuccess"] != null)
{
	<script type="text/javascript">
		toastr.warning('@TempData["unsuccess"]');
	</script>
}