BulkyBookWebNew/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]

public class CoverTypeController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CoverTypeController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }
    public IActionResult Index()
    {
        var obj = _unitOfWork.CoverType.GetAll();
        return View(obj);
    }
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CoverType obj)
    {

        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("Error", "Something wrong, Check your data");
            return View(obj);
        }

        var isNameAlreadyTaken = _unitOfWork.CoverType.GetFirstOrDefault(e => e.Name == obj.Name);

        if (isNameAlreadyTaken != null)
        {
            ModelState.AddModelError("name", "Your Name Cover Type is already taken");
            return View(obj);
        }
        _unitOfWork.CoverType.Add(obj);
        await _unitOfWork.Save();
        TempData["success"] = "Cover Type created succesfully";
        return RedirectToAction("Index");
    }
    public IActionResult Edit(int id)
    {
        var obj = _unitOfWork.CoverType.GetFirstOrDefault(e => e.Id == id);
        if (obj == null)
        {
            TempData["unsuccess"] = "The data is not in our server";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(CoverType obj)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("Error", "Something wrong, Check your data");
            return View(obj);
        }

        var isNameAlreadyTaken = _unitOfWork.CoverType.GetFirstOrDefault(e => e.Name == obj.Name, noTrack: true);

        if (isNameAlreadyTaken != null && isNameAlreadyTaken.Id != obj.Id)
        {
            ModelState.AddModelError("name", "Your Name Cover Type is already taken");
            return View(obj);
        }
        _unitOfWork.CoverType.Update(obj);
        await _unitOfWork.Save();
        TempData["success"] = "Cover Type edited succesfully";
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        var obj = _unitOfWork.CoverType.GetFirstOrDefault(e => e.Id == id);
        if (obj == null)
        {
            TempData["unsuccess"] = "The data is not in our server";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(CoverType obj)
    {
        _unitOfWork.CoverType.Remove(obj);
        await _unitOfWork.Save();
        TempData["success"] = "Cover Type deleted succesfully";
        return RedirectToAction("Index");
    }
}

BulkyBookWebNew/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post" class="container">
	@*<div asp-validation-summary="All"></div>*@

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create CoverType</h2>
			<hr />
		</div>

		<div class="mb-3">
			<label class="form-label" asp-for="Name">Name <span class="text-danger">*</span></label>
			<input class="form-control" asp-for="Name" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back to List</a>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyBookWebNew/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" class="container">
	@*<div asp-validation-summary="All"></div>*@

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create CoverType</h2>
			<hr />
		</div>

		<div class="mb-3">
			<label class="form-label" asp-for="Name">Name <span class="text-danger">*</span></label>
			<input class="form-control" asp-for="Name" disabled/>
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary" style="width: 175px">Create</button>
		<a asp-controller="CoverType" asp-action="Index" class="ms-2 btn btn-secondary border border-2" style="width: 175px">Back to List</a>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyBookWebNew/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post" class="container">
	@*<div asp-validation-summary="All"></div>*@

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create CoverType</h2>
			<hr />
		</div>

		<div class="mb-3">
			<label class="form-label" asp-for="Name">Name <span class="text-danger">*</span></label>
			<input class="form-control" asp-for="Name" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back to List</a>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyBookWebNew/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>

<div class="container p-3 mb-5">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">CoverType List</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="CoverType" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i> &nbsp; Create CoverType</a>
		</div>
	</div>
	<br /><br />

	<table class="table table-bordered table-striped" style="width: 100%">
		<thead>
			<tr class="text-center align-middle">
				<th>
					CoverType Name
				</th>
				<th>Options</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td width="50%">
					@item.Name
					</td>
					<td width="20%">
						<div class="w-75 btn-group d-flex mx-auto" role="group">
							<a asp-controller="CoverType" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info d-flex flex-column" style="width: 50px"><i class="bi bi-pencil-square"></i> Edit</a>
							<a asp-controller="CoverType" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger d-flex flex-column" style="width: 50px"><i class="bi bi-trash-fill"></i> Delete</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>